### ISSUE TITLE
Create a Chessboard

### ISSUE THREAD

**Issue by marte1337** [marte1337/capstone-project#1]
## Value proposition

As a user
I want to have a chessboard
in order to play chess

## Description

![Screenshot 2023-04-25 at 16 27 39](https://user-images.githubusercontent.com/54943747/234309233-66b77834-5d6b-4511-8740-66704c135b29.png)

## Acceptance criteria

- [x] a basic chessboard on MainBoard-Page

## Tasks

- [x] create a branch
- [x] create a MainBoardPage
- [x] create a MainBoard-Component
- [x] create a chessboard with the react-chessboard library

**Comment by NikRoe** [comment]
Looks good 💪
