### ISSUE TITLE
Player VS RandomMoveMachine Zombie-Mode

### ISSUE THREAD

**Issue by marte1337** [marte1337/capstone-project#15]
## Value proposition

As a user
I want to play the zombie mode against the randomMoveMachine
in order to have more fun

## Description

![Image](https://github.com/marte1337/capstone-project/assets/54943747/9ef9e8c3-f3d4-42ba-bcfd-3722ab9b22e5)

## Acceptance criteria

- [x] player vs randomMoveMachine zombie-mode playlist availabe
- [x] play a game where killed chess pieces are revived for the active player
- [x] on game over, the game over sign should appear and the game data should be logged in the console

## Tasks

- [x] create a branch
- [x] create a PlayerVsRandomMove-Component
- [x] import the zombie-mode from the PlayerVsPlayer component to the PlayerVsRandomMove-Component
- [x] keep track of the move history
- [x] keep track of the fen history
- [x] update the routing, so that two boards are available at the landing page:  PlayerVSPlayer + PlayerVsRandomMove

**Comment by marte1337** [comment]
Thanks!
