### ISSUE TITLE
Operation 'Quality of Life': tutorials / replay function

### ISSUE THREAD

**Issue by marte1337** [marte1337/capstone-project#16]
## Value proposition

As a user
I want see a few tutorials and a the replay of a finished game
in order to get a better understanding of the game mechanics

## Description

![Image](https://github.com/marte1337/capstone-project/assets/54943747/90d16a60-0b2b-415e-90e3-d8bab02761ad)
![Image](https://github.com/marte1337/capstone-project/assets/54943747/76e31258-db0a-4027-bfd6-40539dc864db)

## Acceptance criteria

- [x] Tutorials are available at the main menu
- [x] While playing a tutorial its possible to skip to the next one
- [x] When a game against the RandomMoveMachine is finished a replay option appears
- [x] Two buttons navigate through the replay

## Tasks

- [x] create a branch
- [x] create a TutorialBoardBoard component and a tutorial page
- [x] create some tutorials, implement TutorialBoard component into the tutorial page
- [x] implement the replay option inside the PlayerVsRandomMove component

**Comment by marte1337** [comment]
Thanks! I´ll update the wireframe asap.
