### ISSUE TITLE
Display player names

### ISSUE THREAD

**Issue by marte1337** [marte1337/capstone-project#2]
## Value proposition

As a user
I want to see my playername and my opponents name
in order to know who I am and who I am playing against

## Description

![Screenshot 2023-04-25 at 16 28 06](https://user-images.githubusercontent.com/54943747/234314074-0239ac14-011c-4427-9ba7-75742baf968c.png)

## Acceptance criteria

- [x] Player-Name is displayed
- [x] Opponent-Name is displayed

## Tasks

- [x] create a branch
- [x] create a PlayerNameDisplay-Component
- [x] implement PlayerNameDisplay-Component in MainBoardPage
- [x] pass down static props for now
