### ISSUE TITLE
Real Player Game Lobby

### ISSUE THREAD

**Issue by marte1337** [marte1337/capstone-project#22]
## Value proposition

As a user I want to play against real players
in order to have full fletched game experience

## Description

![Image](https://github.com/marte1337/capstone-project/assets/54943747/93a6a717-9129-463c-93b3-d67305986ae1)

## Acceptance criteria

- [x] A user can join a game lobby with their individual player name
- [x] Inside the game lobby users can chat and join a 1vs1 board to play against each other

## Tasks

- [x] create a branch
- [x] initiate interactivity with the pusher api
- [x] create a prelobby page where users can enter their player name
- [x] create a gamelobby page where users can chat and join a 1vs1 board
- [x] revamp the multiplayer page to have true multiplayer capabilities
