### ISSUE TITLE
Enhanced responsiveness

### ISSUE THREAD

**Issue by marte1337** [marte1337/capstone-project#27]
## Value proposition

As a user
I want have a enhanced responsiveness
in order to play the game on multiple devices

## Description

![Image](https://github.com/marte1337/capstone-project/assets/54943747/90d16a60-0b2b-415e-90e3-d8bab02761ad)
![Image](https://github.com/marte1337/capstone-project/assets/54943747/76e31258-db0a-4027-bfd6-40539dc864db)

## Acceptance criteria

- [ ] Enhance responsive design on all pages
- [ ] In-game chat moves next to chessboard on very large viewports

## Tasks

- [ ] create a branch
- [ ] enhance responsiveness to the individual pages
