### ISSUE TITLE
Display previous move info

### ISSUE THREAD

**Issue by marte1337** [marte1337/capstone-project#3]
## Value proposition

As a user
I want to see the information about the previous move and a check info
in order to get a better orientation in the game

## Description

![Screenshot 2023-04-25 at 16 28 06](https://user-images.githubusercontent.com/54943747/234314074-0239ac14-011c-4427-9ba7-75742baf968c.png)

## Acceptance criteria

- [x] previous move is displayed
- [x] a promt is displayed if king is in check

## Tasks

- [x] create a branch
- [x] request the above stated data from the chess.js library ans store it as useState in RandomMoveEngine
- [x] create a MoveInfo-Component
- [x] implement MoveInfo-Component in RandomMoveEngine.js and pass down props

**Comment by t0bbl** [comment]
cooler kommentar

**Comment by t0bbl** [comment]
mhhhh it smells fishy in here. like change...
