### ISSUE TITLE
respawn zombie pieces

### ISSUE THREAD

**Issue by marte1337** [marte1337/capstone-project#5]
## Value proposition

As a user
I want to have zombie pieces respawning every time a piece gets captured
in order to have more fun

## Description

![Screenshot 2023-04-25 at 16 28 06](https://user-images.githubusercontent.com/54943747/234314074-0239ac14-011c-4427-9ba7-75742baf968c.png)

## Acceptance criteria

- [x] Every time a black piece gets captured, a white zombie piece will spawn and vice versa.
- [x] Move history is still intact

## Tasks

- [x] create a branch
- [x] create a PlayerVsPlayer Component
- [x] manipulate the the chess.js library so that zombie pieces can spawn
- [x] keep track of the movehistory
