### ISSUE TITLE
move option preview

### ISSUE THREAD

**Issue by marte1337** [marte1337/capstone-project#8]
## Value proposition

As a user
I want to see a preview of the possible moves a certain piece is allowed to do, as soon as i click on it,
in order to have a visual representation of my options are

## Description
![Image](https://user-images.githubusercontent.com/54943747/235096628-e3013bb0-8711-40a4-b4bd-d2c1e939e008.png)

## Acceptance criteria

- [ ] pieces respond to click input
- [ ] visual representation of possible moves 

## Tasks

- [ ] create a branch
- [ ] setup react-chessboard library in RandomMoveEngine.js to match above stated requirements

**Comment by t0bbl** [comment]
LGTM
